---
title: "About"
---

Broadcasted by the BBC, Doctor Who is a British Science-Fiction TV Series about a time travelling alien and their companion. To date, 319 stories have been broadcast: 155 from the Classic Era (1963-1989); 1 film (1996); and 163, since the Revival Era began in 2005.

Furthermore, there have been 4 eras of Showrunner since the return in 2005: Russell T Davis (2005-2010), Steven Moffat (2010 -2017), Chris Chibnall (2018-2021), and Russell T Davies (2023 - Present).

Additionally, there have been 7 incarnations of The Doctor, since it's return: Ninth Doctor (Series One), Tenth Doctor (Series Two to 2008-2010 Specials), Eleventh Doctor (Series Five to 2013 Specials), Twelfth Doctor (Series Eight to Series Ten), Thirteenth Doctor (Series Eleven to Series Thirteen), Fourteenth Doctor (2023 Specials), and the Fifteenth Doctor (Series Fourteen and Fifteen). 

The show itself airs on a Saturday - bar during the Thirteenth Doctor's tenure, where it aired on a Sunday - and is also available in the UK on iPlayer. 